- hosts: namth22
  vars:
      ansible_site_path: "C:\\inetpub\\sites"
      ansible_site_name: "namth22-demo-iis"

  tasks:

    - name: Install IIS (Web-Server and Web-Common-Http)
      win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: present

    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature

    - name: Reboot if installing Web-Server feature requires it
      win_reboot:
      when: win_feature.reboot_required

    # Start a website
    - name: Create directory structure
      win_file:
        path: "{{ ansible_site_path }}"
        state: directory
    
    - name: Create directory structure
      win_file:
        path: "{{ ansible_site_path }}\\{{ ansible_site_name }}"
        state: directory

    - name: Acme IIS site
      win_iis_website:
        name: "{{ ansible_site_name }}"
        state: started
        port: 8085
        ip: localhost
        application_pool: "{{ ansible_site_name }}"
        physical_path: "{{ ansible_site_path }}\\{{ ansible_site_name }}"
        parameters: logfile.directory:c:\sites\logs
      register: website

    # # Remove Default Web Site and the standard port 80 binding
    # - name: Remove Default Web Site
    #   win_iis_website:
    #     name: "Default Web Site"
    #     state: absent